import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Application, Job, AuditEntry, CvProfile } from "@/context/AppContext";
import { CAA_LOGO_BASE64 } from "@/lib/caa-logo-base64";

const NAVY: [number, number, number] = [13, 36, 84];
const ACCENT: [number, number, number] = [201, 162, 39];

function header(doc: jsPDF, title: string, subtitle?: string) {
  // White background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 210, 297, "F");

  // Logo (left side)
  try { doc.addImage(CAA_LOGO_BASE64, "JPEG", 10, 8, 22, 22); } catch {}

  // Organisation name (right of logo, vertically centered)
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("UGANDA CIVIL AVIATION AUTHORITY", 36, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.text("Entebbe International Airport  |  P.O. Box 5536, Kampala, Uganda", 36, 23);
  doc.text("Tel: +256 312 352 000  |  aviation@caa.go.ug  |  www.caa.go.ug", 36, 28);

  // Blue separator line (matching the letter's blue rule)
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.8);
  doc.line(10, 33, 200, 33);
  doc.setFillColor(...ACCENT);
  doc.rect(10, 33.8, 190, 0.4, "F");

  // Reference and date (like a formal letter)
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Our Ref: UCAA/HR/PORTAL", 10, 40);
  doc.text(new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), 200, 40, { align: "right" });

  // Document title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text(title.toUpperCase(), 10, 50);
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.3);
  doc.line(10, 52, Math.min(10 + doc.getTextWidth(title.toUpperCase()), 200), 52);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(subtitle, 10, 58);
  }
}

function footer(doc: jsPDF, actor: string) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    // Footer rule
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(10, 283, 200, 283);
    doc.setFontSize(7.5);
    doc.setTextColor(80, 80, 80);
    doc.setFont("helvetica", "normal");
    doc.text("Uganda Civil Aviation Authority — Confidential HR Document. Not for external distribution.", 10, 287);
    doc.text(`Generated by ${actor}`, 10, 291);
    doc.text(`Page ${i} of ${pages}`, 200, 291, { align: "right" });
  }
}

export function downloadJobsReport(jobs: Job[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Vacancies Report", `${jobs.length} listings as at ${new Date().toLocaleDateString()}`);
  autoTable(doc, {
    startY: 65,
    head: [["#", "Title", "Department", "Band", "Visibility", "Closes", "Min Age", "Exp (yrs)"]],
    body: jobs.map((j) => [j.id, j.title, j.dept, j.salaryBand, j.visibility, j.closes, j.minAge, j.requiredExperience]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-vacancies-${Date.now()}.pdf`);
}

export function downloadJobRequirementsReport(jobs: Job[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Job Requirement Report", `${jobs.length} listings as at ${new Date().toLocaleDateString()}`);
  autoTable(doc, {
    startY: 65,
    head: [["Title", "Department", "Required Qualification", "Min Exp (yrs)", "Min Age", "Salary Band", "Salary Range", "Location"]],
    body: jobs.map((j) => [j.title, j.dept, j.requiredQualification, j.requiredExperience, j.minAge, j.salaryBand, j.salary, j.location]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-job-requirements-${Date.now()}.pdf`);
}

export function downloadApplicationsReport(apps: Application[], jobs: Job[], actor: string, title = "Applications Report") {
  const doc = new jsPDF();
  const byStatus: Record<string, number> = {};
  apps.forEach((a) => (byStatus[a.status] = (byStatus[a.status] ?? 0) + 1));
  header(doc, title, `${apps.length} applications across ${new Set(apps.map((a) => a.jobId)).size} vacancies`);

  autoTable(doc, {
    startY: 65,
    head: [["Status", "Count"]],
    body: Object.entries(byStatus).map(([s, n]) => [s, n]),
    headStyles: { fillColor: NAVY, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    tableWidth: 80,
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    head: [["#", "Candidate", "Email", "Role", "Department", "Submitted", "Status"]],
    body: apps.map((a) => {
      const job = jobs.find((j) => j.id === a.jobId);
      return [a.id, a.candidateName ?? "—", a.candidateEmail ?? "—", a.title, job?.dept ?? a.dept, a.date, a.status];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-applications-${Date.now()}.pdf`);
}

export function downloadDepartmentSummary(jobs: Job[], apps: Application[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Departmental Recruitment Summary", "Active listings and pipeline by department");
  const depts = Array.from(new Set(jobs.map((j) => j.dept)));
  const rows = depts.map((d) => {
    const dJobs = jobs.filter((j) => j.dept === d);
    const dApps = apps.filter((a) => dJobs.some((j) => j.id === a.jobId));
    return [d, dJobs.length, dApps.length, dApps.filter((a) => a.status === "Shortlisted").length, dApps.filter((a) => a.status === "Offered").length];
  });
  autoTable(doc, {
    startY: 65,
    head: [["Department", "Listings", "Applications", "Shortlisted", "Offered"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-dept-summary-${Date.now()}.pdf`);
}

export function downloadAuditLog(audit: AuditEntry[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Admin Audit Log", `${audit.length} most recent actions`);
  autoTable(doc, {
    startY: 65,
    head: [["Timestamp", "Actor", "Role", "Action", "Target"]],
    body: audit.map((e) => [new Date(e.at).toLocaleString(), e.actor, e.role, e.action, e.target ?? ""]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-audit-${Date.now()}.pdf`);
}

function openPdfInTab(doc: jsPDF, fallbackName: string) {
  try {
    const url = doc.output("bloburl") as unknown as string;
    const w = window.open(url, "_blank");
    if (!w) doc.save(fallbackName);
  } catch {
    doc.save(fallbackName);
  }
}

export function downloadCandidateCv(cv: CvProfile, app: Application | undefined, actor: string, opts?: { preview?: boolean }) {
  const doc = new jsPDF();
  const name = `${cv.personal.firstName} ${cv.personal.lastName}`.trim() || app?.candidateName || "Candidate";
  header(doc, `Candidate Dossier — ${name}`, app ? `${app.title} • Submitted ${app.date} • ${app.status}` : "CV on file");

  let y = 68;
  doc.setTextColor(13, 36, 84); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text("Personal Details", 12, y); y += 5;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
  const p = cv.personal;
  const personal = [
    ["Full name", `${p.firstName} ${p.otherName ?? ""} ${p.lastName}`.replace(/\s+/g, " ").trim()],
    ["Date of birth", p.dob || "—"], ["Gender", p.gender || "—"],
    ["Nationality", p.nationality || "—"], ["NIN", p.nin || "—"],
    ["Phone", p.phone || "—"], ["Email", p.email || "—"],
    ["Address", p.address || "—"],
  ];
  autoTable(doc, { startY: y, body: personal, theme: "plain", styles: { fontSize: 9, cellPadding: 1.5 }, columnStyles: { 0: { fontStyle: "bold", cellWidth: 38, textColor: [90, 90, 90] } } });
  y = (doc as any).lastAutoTable.finalY + 6;

  if (cv.qualifications.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Qualifications", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Level", "Course / Award", "Institution", "Year"]],
      body: cv.qualifications.map((q) => [q.level, q.course || q.school || "—", q.institution || q.school || "—", q.year || "—"]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (cv.experience.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Work Experience", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Title", "Organisation", "Start", "End", "Notes"]],
      body: cv.experience.map((e) => [e.title, e.organisation, e.start, e.end, e.description]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (cv.skills.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Skills", 12, y); y += 5;
    doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
    doc.text(cv.skills.join(" · "), 12, y, { maxWidth: 186 });
    y += 8;
  }

  if (cv.referees.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Referees", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Name", "Title", "Organisation", "Phone", "Email"]],
      body: cv.referees.filter((r) => r.name).map((r) => [r.name, r.title, r.organisation, r.phone, r.email]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
  }

  footer(doc, actor);
  const file = `caa-candidate-${name.replace(/\s+/g, "-").toLowerCase()}.pdf`;
  if (opts?.preview) openPdfInTab(doc, file); else doc.save(file);
}

export type StaffRecord = {
  empNo: string; firstName: string; lastName: string;
  dept: string; position: string; email: string; joined: string; status: string;
};

export function downloadInternsReport(apps: Application[], jobs: Job[], actor: string) {
  const doc = new jsPDF();
  const sorted = [...apps].filter((a) => a.cgpa !== undefined).sort((a, b) => (b.cgpa ?? 0) - (a.cgpa ?? 0));
  header(doc, "Intern Applications — CGPA Ranking", `${sorted.length} applications ranked by academic performance`);
  autoTable(doc, {
    startY: 65,
    head: [["Rank", "Candidate", "Email", "Position", "CGPA", "University", "Status", "Submitted"]],
    body: sorted.map((a, i) => {
      const job = jobs.find((j) => j.id === a.jobId);
      return [i + 1, a.candidateName ?? "—", a.candidateEmail ?? "—", job?.title ?? a.title, a.cgpa?.toFixed(1) ?? "—", a.university ?? "—", a.status, a.date];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-interns-cgpa-${Date.now()}.pdf`);
}

export function downloadApplicationSummary(
  app: Application,
  candidateName: string,
  candidateEmail: string,
  job?: Job,
) {
  const doc = new jsPDF();
  const refNo = `UCAA/REC/${String(app.id).padStart(5, "0")}/${new Date().getFullYear()}`;
  header(doc, "Application Confirmation", `${app.title} · Ref: ${refNo}`);

  let y = 68;

  // Candidate block
  doc.setTextColor(...NAVY); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text("Candidate Details", 12, y); y += 2;
  autoTable(doc, {
    startY: y,
    theme: "plain",
    body: [
      ["Full name",           candidateName || "—"],
      ["Email address",       candidateEmail || "—"],
      ["Account type",        "Registered Candidate"],
    ],
    styles: { fontSize: 9, cellPadding: 1.8 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 48, textColor: [90, 90, 90] } },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // Application block
  doc.setTextColor(...NAVY); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text("Application Details", 12, y); y += 2;
  autoTable(doc, {
    startY: y,
    theme: "plain",
    body: [
      ["Reference number",    refNo],
      ["Position applied",    app.title],
      ["Department",          job?.dept ?? app.dept],
      ["Location",            job?.location ?? "—"],
      ["Salary band",         job?.salaryBand ? `${job.salaryBand} (${job.salary})` : "—"],
      ["Employment type",     job?.type ?? "—"],
      ["Application status",  app.status],
      ["Profile completion",  `${app.completion}%`],
      ["Date submitted",      app.date],
      ["Vacancy closes",      job?.closes ?? "—"],
    ],
    styles: { fontSize: 9, cellPadding: 1.8 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 48, textColor: [90, 90, 90] } },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Next steps box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(10, y, 190, 38, 2, 2, "F");
  doc.setDrawColor(...NAVY); doc.setLineWidth(0.3);
  doc.roundedRect(10, y, 190, 38, 2, 2, "S");
  doc.setTextColor(...NAVY); doc.setFont("helvetica", "bold"); doc.setFontSize(10);
  doc.text("What happens next?", 15, y + 7);
  doc.setTextColor(50, 50, 50); doc.setFont("helvetica", "normal"); doc.setFontSize(8.5);
  const steps = [
    "1. Your application is being reviewed by the CAA Uganda HR team.",
    "2. Shortlisted candidates will be contacted within 14 working days.",
    "3. All communication will be sent to your registered email address.",
    "4. Do not call UCAA offices to enquire about application status — check your dashboard.",
  ];
  steps.forEach((s, i) => doc.text(s, 15, y + 14 + i * 5.5));
  y += 48;

  // Authenticity note
  doc.setFontSize(7.5); doc.setTextColor(100, 100, 100); doc.setFont("helvetica", "italic");
  doc.text("This document was generated automatically from the UCAA e-Recruitment Portal. It serves as proof of application submission only.", 10, y, { maxWidth: 190 });
  doc.text("Uganda Civil Aviation Authority does not charge any recruitment fees at any stage of the process.", 10, y + 5, { maxWidth: 190 });

  footer(doc, candidateName || "Candidate");
  doc.save(`caa-application-${refNo.replace(/\//g, "-")}.pdf`);
}

export function downloadStaffReport(staff: StaffRecord[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Internal Staff Register", `${staff.length} verified CAA staff records`);
  autoTable(doc, {
    startY: 65,
    head: [["Emp No.", "Full Name", "Department", "Position", "Email", "Joined", "Status"]],
    body: staff.map((s) => [s.empNo, `${s.firstName} ${s.lastName}`, s.dept, s.position, s.email, s.joined, s.status]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-staff-register-${Date.now()}.pdf`);
}

export function downloadShortlistedDossiers(
  apps: Application[],
  jobs: Job[],
  cvByEmail: Record<string, CvProfile>,
  actor: string,
) {
  const doc = new jsPDF();
  header(
    doc,
    "Shortlisted Candidates — Bulk Dossier",
    `${apps.length} shortlisted candidate${apps.length === 1 ? "" : "s"} across ${new Set(apps.map((a) => a.jobId)).size} vacancy(ies)`,
  );

  autoTable(doc, {
    startY: 65,
    head: [["#", "Candidate", "Email", "Role", "Department", "Submitted"]],
    body: apps.map((a, i) => {
      const j = jobs.find((x) => x.id === a.jobId);
      return [i + 1, a.candidateName ?? "—", a.candidateEmail ?? "—", a.title, j?.dept ?? a.dept, a.date];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  apps.forEach((a, idx) => {
    doc.addPage();
    const name = a.candidateName || "Candidate";
    const job = jobs.find((j) => j.id === a.jobId);
    header(
      doc,
      `Dossier ${idx + 1} of ${apps.length} — ${name}`,
      `${a.title}${job ? ` • ${job.dept}` : ""} • Submitted ${a.date}`,
    );

    let y = 68;
    doc.setTextColor(13, 36, 84); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
    doc.text("Application Summary", 12, y); y += 4;
    autoTable(doc, {
      startY: y,
      theme: "plain",
      body: [
        ["Application ID", String(a.id)],
        ["Candidate", name],
        ["Email", a.candidateEmail ?? "—"],
        ["Role applied", a.title],
        ["Department", job?.dept ?? a.dept],
        ["Salary band", job?.salaryBand ?? "—"],
        ["Visibility", job?.visibility ?? "—"],
        ["Submitted", a.date],
        ["Status", a.status],
        ["Profile completion", `${a.completion}%`],
      ],
      styles: { fontSize: 9, cellPadding: 1.5 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 48, textColor: [90, 90, 90] } },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    const cv = a.candidateEmail ? cvByEmail[a.candidateEmail.toLowerCase()] : undefined;
    if (cv) {
      const p = cv.personal;
      doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
      doc.text("Personal Details", 12, y); y += 4;
      autoTable(doc, {
        startY: y, theme: "plain",
        body: [
          ["Full name", `${p.firstName} ${p.otherName ?? ""} ${p.lastName}`.replace(/\s+/g, " ").trim() || "—"],
          ["Date of birth", p.dob || "—"], ["Gender", p.gender || "—"],
          ["Nationality", p.nationality || "—"], ["NIN", p.nin || "—"],
          ["Phone", p.phone || "—"], ["Address", p.address || "—"],
        ],
        styles: { fontSize: 9, cellPadding: 1.5 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 38, textColor: [90, 90, 90] } },
      });
      y = (doc as any).lastAutoTable.finalY + 6;

      if (cv.qualifications.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Qualifications", 12, y);
        autoTable(doc, {
          startY: y + 2,
          head: [["Level", "Course / Award", "Institution", "Year"]],
          body: cv.qualifications.map((q) => [q.level, q.course || q.school || "—", q.institution || q.school || "—", q.year || "—"]),
          headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
        });
        y = (doc as any).lastAutoTable.finalY + 6;
      }

      if (cv.experience.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Work Experience", 12, y);
        autoTable(doc, {
          startY: y + 2,
          head: [["Title", "Organisation", "Start", "End", "Notes"]],
          body: cv.experience.map((e) => [e.title, e.organisation, e.start, e.end, e.description]),
          headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
        });
        y = (doc as any).lastAutoTable.finalY + 6;
      }

      if (cv.skills.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Skills", 12, y); y += 5;
        doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
        doc.text(cv.skills.join(" · "), 12, y, { maxWidth: 186 });
      }
    } else {
      doc.setFont("helvetica", "italic"); doc.setFontSize(9); doc.setTextColor(120, 120, 120);
      doc.text("Full CV profile not available offline for this candidate. Open the candidate record in the HR Console to view the live dossier.", 12, y, { maxWidth: 186 });
    }
  });

  footer(doc, actor);
  doc.save(`caa-shortlist-dossiers-${Date.now()}.pdf`);
}

export type ScreeningReportEntry = {
  id: number; name: string; email: string; role: string; dept: string; date: string;
  pass: boolean; failedChecks: string[];
};

export function downloadScreeningReport(
  entries: ScreeningReportEntry[],
  actor: string,
) {
  const doc = new jsPDF();
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const passed = entries.filter((e) => e.pass);
  const failed  = entries.filter((e) => !e.pass);
  const pct = entries.length ? Math.round((passed.length / entries.length) * 100) : 0;

  header(doc, "Automated Screening Report", `Screened ${entries.length} applicant${entries.length !== 1 ? "s" : ""} — ${now}`);

  // ── Summary box ──────────────────────────────────────────────────────────
  let y = 65;
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(10, y, 190, 22, 2, 2, "F");
  doc.setDrawColor(...NAVY); doc.setLineWidth(0.3);
  doc.roundedRect(10, y, 190, 22, 2, 2, "S");

  const cols = [
    { label: "Total Screened", value: String(entries.length), x: 35 },
    { label: "Passed (Shortlisted)", value: String(passed.length), x: 80 },
    { label: "Failed (Declined)", value: String(failed.length), x: 125 },
    { label: "Pass Rate", value: `${pct}%`, x: 170 },
  ];
  cols.forEach(({ label, value, x }) => {
    doc.setFont("helvetica", "bold"); doc.setFontSize(14); doc.setTextColor(...NAVY);
    doc.text(value, x, y + 12, { align: "center" });
    doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(80, 80, 80);
    doc.text(label, x, y + 19, { align: "center" });
  });
  y += 28;

  // ── By-position summary ────────────────────────────────────────────────
  const byRole: Record<string, { screened: number; pass: number }> = {};
  entries.forEach((e) => {
    if (!byRole[e.role]) byRole[e.role] = { screened: 0, pass: 0 };
    byRole[e.role].screened++;
    if (e.pass) byRole[e.role].pass++;
  });
  const roleRows = Object.entries(byRole).map(([role, { screened, pass: p }]) => [
    role, screened, p, screened - p, `${Math.round((p / screened) * 100)}%`,
  ]);

  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...NAVY);
  doc.text("RESULTS BY POSITION", 10, y); y += 2;
  autoTable(doc, {
    startY: y,
    head: [["Position", "Screened", "Pass", "Fail", "Pass Rate"]],
    body: roleRows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 0: { cellWidth: 85 }, 4: { fontStyle: "bold" } },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Passed candidates ──────────────────────────────────────────────────
  if (passed.length > 0) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(16, 111, 74);
    doc.text(`SHORTLISTED — ${passed.length} CANDIDATE${passed.length !== 1 ? "S" : ""}`, 10, y); y += 2;
    autoTable(doc, {
      startY: y,
      head: [["#", "Candidate", "Email", "Position", "Department", "Applied"]],
      body: passed.map((e, i) => [i + 1, e.name, e.email, e.role, e.dept, e.date]),
      headStyles: { fillColor: [16, 111, 74], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 7.5, cellPadding: 2 },
      alternateRowStyles: { fillColor: [240, 253, 244] },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Failed candidates ─────────────────────────────────────────────────
  if (failed.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(220, 38, 38);
    doc.text(`NOT MEETING CRITERIA — ${failed.length} CANDIDATE${failed.length !== 1 ? "S" : ""}`, 10, y); y += 2;
    autoTable(doc, {
      startY: y,
      head: [["#", "Candidate", "Position", "Applied", "Failed Checks"]],
      body: failed.map((e, i) => [i + 1, e.name, e.role, e.date, e.failedChecks.join(", ") || "—"]),
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 7.5, cellPadding: 2 },
      alternateRowStyles: { fillColor: [254, 242, 242] },
    });
  }

  // ── Disclaimer ────────────────────────────────────────────────────────
  const lastPage = doc.getNumberOfPages();
  doc.setPage(lastPage);
  const ly = (doc as any).lastAutoTable?.finalY ?? 240;
  if (ly + 18 < 280) {
    doc.setFont("helvetica", "italic"); doc.setFontSize(7.5); doc.setTextColor(120, 120, 120);
    doc.text(
      "This report was generated automatically by the UCAA e-Recruitment Portal. Results are based on application data and CV information on file. " +
      "Administrators should review borderline cases before final confirmation. This document is strictly confidential.",
      10, ly + 8, { maxWidth: 190 },
    );
  }

  footer(doc, actor);
  doc.save(`caa-screening-report-${Date.now()}.pdf`);
}

export function downloadOfferLetter(app: Application, job: Job | undefined, actor: string) {
  const doc = new jsPDF();
  const ref = `UCAA/HR/${new Date().getFullYear()}/${String(app.id).padStart(4, "0")}`;
  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const reportingDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
    .toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const firstName = (app.candidateName ?? "Applicant").split(" ")[0];

  header(doc, "LETTER OF OFFER — EMPLOYMENT");

  let y = 68;

  // Candidate address block
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(30, 30, 30);
  doc.text(app.candidateName ?? "Applicant", 10, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(80, 80, 80);
  doc.text("Uganda", 10, y + 5);
  if (app.candidateEmail) doc.text(app.candidateEmail, 10, y + 10);
  doc.text(today, 200, y + 10, { align: "right" });
  y += 22;

  doc.setFontSize(8.5);
  doc.text(`Ref: ${ref}`, 10, y);
  y += 9;

  // Salutation
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(30, 30, 30);
  doc.text(`Dear ${firstName},`, 10, y);
  y += 8;

  // Heading
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY);
  const heading = `OFFER OF EMPLOYMENT — ${app.title.toUpperCase()}`;
  doc.text(heading, 10, y);
  doc.setDrawColor(...NAVY); doc.setLineWidth(0.3);
  doc.line(10, y + 2, Math.min(10 + doc.getTextWidth(heading), 200), y + 2);
  y += 10;

  // Opening paragraph
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(30, 30, 30);
  const wrap = (text: string, startY: number): number => {
    const lines = doc.splitTextToSize(text, 190);
    doc.text(lines, 10, startY);
    return startY + lines.length * 5.5;
  };
  y = wrap(
    `Following your successful performance throughout the Uganda Civil Aviation Authority (UCAA) selection process for the above-named position, we are pleased to extend to you this offer of employment, subject to the terms and conditions set out below.`,
    y,
  );
  y += 6;

  // Terms table
  autoTable(doc, {
    startY: y,
    body: [
      ["Position:",            app.title],
      ["Department:",          job?.dept ?? app.dept],
      ["Grade / Salary Band:", job?.salaryBand ?? "As per HR schedule"],
      ["Monthly Gross Salary:", job?.salary ?? "As per HR schedule"],
      ["Employment Type:",     job?.type ?? "Full-time, Permanent"],
      ["Place of Work:",       job?.location ?? "Entebbe International Airport, Kampala"],
      ["Reporting Date:",      reportingDate],
    ],
    styles: { fontSize: 9.5, cellPadding: 3, lineColor: [220, 225, 235], lineWidth: 0.2 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 58, textColor: NAVY }, 1: { textColor: [30, 30, 30] } },
    tableLineWidth: 0.2, tableLineColor: [220, 225, 235],
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  y = wrap(
    `This offer is conditional upon: (a) satisfactory completion of a pre-employment medical examination at an institution approved by UCAA; (b) verification and authentication of all academic and professional credentials submitted; (c) satisfactory reference and background checks; and (d) signing of the UCAA Employment Contract within five (5) working days of receipt of this letter.`,
    y,
  );
  y += 6;

  y = wrap(
    `You are required to report to the Human Resources Department at UCAA Head Office, Entebbe International Airport, on the reporting date stated above. Please carry originals and photocopies of: all academic certificates and transcripts; your National Identity Card (NIN); two recent passport-size photographs; and any other supporting documents submitted with your application.`,
    y,
  );
  y += 8;

  doc.text("We look forward to welcoming you to the UCAA family. Congratulations.", 10, y);
  y += 10;

  // Signature block
  doc.text("Yours sincerely,", 10, y);
  y += 14;
  doc.setDrawColor(180, 180, 180); doc.setLineWidth(0.3);
  doc.line(10, y, 80, y);
  y += 5;
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(30, 30, 30);
  doc.text(actor, 10, y);
  y += 5;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(80, 80, 80);
  doc.text("For: Director Human Resources", 10, y);
  y += 4; doc.text("Uganda Civil Aviation Authority", 10, y);
  y += 12;

  // Acceptance tear-off
  if (y + 32 > 275) { doc.addPage(); y = 20; }
  doc.setDrawColor(...NAVY); doc.setLineWidth(0.4);
  doc.roundedRect(10, y, 190, 32, 2, 2, "S");
  doc.setFillColor(247, 249, 252);
  doc.rect(10, y, 190, 8, "F");
  doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...NAVY);
  doc.text("ACCEPTANCE — To be signed and returned to HR within 5 working days", 14, y + 5.5);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
  doc.text(
    `I, ${app.candidateName ?? "________________________________________"}, accept this offer of employment on the terms stated above.`,
    14, y + 15,
  );
  doc.text("Signature: ___________________________    Date: ___________________________", 14, y + 25);

  footer(doc, actor);
  doc.save(`offer-letter-${(app.candidateName ?? "applicant").replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.pdf`);
}

export function downloadJobAdvert(job: Job, actor: string) {
  const doc = new jsPDF();
  header(doc, "Job Advertisement", job.dept);

  // Title block
  let y = 65;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  const titleLines = doc.splitTextToSize(job.title.toUpperCase(), 185);
  doc.text(titleLines, 10, y);
  y += titleLines.length * 7 + 4;

  // Visibility ribbon
  const isInternal = job.visibility === "internal";
  doc.setFillColor(isInternal ? 13 : 16, isInternal ? 36 : 111, isInternal ? 84 : 74);
  doc.roundedRect(10, y, 190, 7, 1, 1, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(
    isInternal ? "INTERNAL VACANCY — CAA STAFF ONLY" : "EXTERNAL VACANCY — OPEN TO ALL QUALIFIED CANDIDATES",
    105, y + 4.8,
    { align: "center" },
  );
  y += 12;

  // Key details table
  autoTable(doc, {
    startY: y,
    head: [["Field", "Details"]],
    body: [
      ["Department",            job.dept],
      ["Location",              job.location],
      ["Employment Type",       job.type],
      ["Salary Band",           `${job.salaryBand} — ${job.salary}`],
      ["Minimum Age",           `${job.minAge} years`],
      ["Required Experience",   `${job.requiredExperience} year(s)`],
      ["Minimum Qualification", job.requiredQualification],
      ["Application Deadline",  job.closes],
    ],
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9.5, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 58, textColor: [60, 60, 60] } },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Description
  if (job.description?.trim()) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text("ABOUT THE ROLE", 10, y);
    y += 1;
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.3);
    doc.line(10, y + 2, 65, y + 2);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(40, 40, 40);
    const descLines = doc.splitTextToSize(job.description, 185);
    doc.text(descLines, 10, y);
    y += descLines.length * 4.8 + 10;
  }

  // How to apply box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(10, y, 190, 32, 2, 2, "F");
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.3);
  doc.roundedRect(10, y, 190, 32, 2, 2, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text("HOW TO APPLY", 15, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(40, 40, 40);
  const howTo = doc.splitTextToSize(
    `Eligible candidates should apply online via the CAA Uganda e-Recruitment Portal at caa.go.ug. ` +
    `Applications must be submitted no later than ${job.closes}. Only shortlisted candidates will be contacted. ` +
    `CAA Uganda does not charge any fees at any stage of recruitment.`,
    178,
  );
  doc.text(howTo, 15, y + 14);

  footer(doc, actor);
  doc.save(`caa-job-advert-${(job.abbr || String(job.id)).toLowerCase()}-${Date.now()}.pdf`);
}

// ─── Time-to-hire report ──────────────────────────────────────────────────────

export function downloadTimeToHireReport(apps: Application[], jobs: Job[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Time-to-Hire Report", `Days from application date to current status — ${new Date().toLocaleDateString()}`);

  const jobMap = new Map(jobs.map((j) => [j.id, j]));
  const byJob: Record<number, { title: string; count: number; totalDays: number; offered: number }> = {};

  apps.forEach((a) => {
    if (!a.jobId) return;
    const d = new Date(a.date);
    if (Number.isNaN(d.getTime())) return;
    const days = Math.round((Date.now() - d.getTime()) / 86_400_000);
    if (!byJob[a.jobId]) byJob[a.jobId] = { title: jobMap.get(a.jobId)?.title ?? `Job #${a.jobId}`, count: 0, totalDays: 0, offered: 0 };
    byJob[a.jobId].count++;
    byJob[a.jobId].totalDays += days;
    if (a.status === "Offered") byJob[a.jobId].offered++;
  });

  const rows = Object.entries(byJob).map(([, v]) => [
    v.title,
    v.count,
    v.offered,
    v.count > 0 ? `${Math.round(v.totalDays / v.count)} days` : "—",
    v.offered > 0 ? `${Math.round(v.totalDays / v.offered)} days` : "—",
  ]);

  autoTable(doc, {
    startY: 65,
    head: [["Job Title", "Applications", "Offers Made", "Avg Days (all)", "Avg Days (to offer)"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  doc.setFontSize(7.5);
  doc.setTextColor(100, 100, 100);
  doc.text("Note: 'Avg Days (all)' counts from application date to today. 'Avg Days (to offer)' applies to offered candidates only.", 10, (doc as any).lastAutoTable.finalY + 6, { maxWidth: 190 });
  footer(doc, actor);
  doc.save(`caa-time-to-hire-${Date.now()}.pdf`);
}

// ─── Diversity summary ────────────────────────────────────────────────────────

export function downloadDiversityReport(apps: Application[], cvStore: Record<string, CvProfile>, actor: string) {
  const doc = new jsPDF();
  header(doc, "Diversity Summary", `Gender breakdown based on available CV data — ${new Date().toLocaleDateString()}`);

  let male = 0, female = 0, other = 0, unknown = 0;
  apps.forEach((a) => {
    const cv = a.candidateEmail ? cvStore[a.candidateEmail.toLowerCase()] : undefined;
    if (!cv) { unknown++; return; }
    const g = (cv.personal?.gender ?? "").toLowerCase();
    if (g === "male") male++;
    else if (g === "female") female++;
    else if (g) other++;
    else unknown++;
  });
  const total = apps.length;
  const pct = (n: number) => total > 0 ? `${((n / total) * 100).toFixed(1)}%` : "—";

  autoTable(doc, {
    startY: 65,
    head: [["Gender", "Count", "Percentage"]],
    body: [
      ["Male",    male,    pct(male)],
      ["Female",  female,  pct(female)],
      ["Other",   other,   pct(other)],
      ["Not available", unknown, pct(unknown)],
      ["TOTAL",   total,   "100%"],
    ],
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    tableWidth: 120,
  });

  const y = (doc as any).lastAutoTable.finalY + 12;
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...NAVY);
  doc.text("Breakdown by Department", 10, y);
  const depts = Array.from(new Set(apps.map((a) => a.dept)));
  const deptRows = depts.map((dept) => {
    const ds = apps.filter((a) => a.dept === dept);
    const dm = ds.filter((a) => { const cv = a.candidateEmail ? cvStore[a.candidateEmail.toLowerCase()] : undefined; return cv?.personal?.gender?.toLowerCase() === "male"; }).length;
    const df = ds.filter((a) => { const cv = a.candidateEmail ? cvStore[a.candidateEmail.toLowerCase()] : undefined; return cv?.personal?.gender?.toLowerCase() === "female"; }).length;
    return [dept, ds.length, dm, df, ds.length > 0 ? `${((df / ds.length) * 100).toFixed(0)}% F` : "—"];
  });
  autoTable(doc, {
    startY: y + 4,
    head: [["Department", "Total", "Male", "Female", "Female %"]],
    body: deptRows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  doc.setFontSize(7.5); doc.setTextColor(100, 100, 100);
  doc.text("Note: gender data available only for candidates who submitted a full CV through the portal.", 10, (doc as any).lastAutoTable.finalY + 6, { maxWidth: 190 });
  footer(doc, actor);
  doc.save(`caa-diversity-${Date.now()}.pdf`);
}

// ─── Screening pass rate ──────────────────────────────────────────────────────

export function downloadScreeningPassRateReport(apps: Application[], jobs: Job[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Screening Pass Rate", `Shortlist conversion by vacancy — ${new Date().toLocaleDateString()}`);

  const jobMap = new Map(jobs.map((j) => [j.id, j]));
  const byJob: Record<number, { title: string; total: number; passed: number; declined: number }> = {};

  apps.forEach((a) => {
    if (!a.jobId) return;
    if (!byJob[a.jobId]) byJob[a.jobId] = { title: jobMap.get(a.jobId)?.title ?? `Job #${a.jobId}`, total: 0, passed: 0, declined: 0 };
    byJob[a.jobId].total++;
    if (["Shortlisted", "Interview", "Offered"].includes(a.status)) byJob[a.jobId].passed++;
    if (a.status === "Declined") byJob[a.jobId].declined++;
  });

  const rows = Object.values(byJob)
    .sort((a, b) => b.total - a.total)
    .map((v) => [
      v.title, v.total, v.passed, v.declined,
      v.total > 0 ? `${((v.passed / v.total) * 100).toFixed(1)}%` : "—",
    ]);

  autoTable(doc, {
    startY: 65,
    head: [["Job Title", "Total Apps", "Shortlisted+", "Declined", "Pass Rate"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  doc.setFontSize(7.5); doc.setTextColor(100, 100, 100);
  doc.text("Pass rate = (Shortlisted + Interview + Offered) ÷ Total applicants per vacancy.", 10, (doc as any).lastAutoTable.finalY + 6, { maxWidth: 190 });
  footer(doc, actor);
  doc.save(`caa-screening-pass-rate-${Date.now()}.pdf`);
}

// ─── Applicants per closing date ──────────────────────────────────────────────

export function downloadApplicantsPerClosingDateReport(
  apps: Application[], jobs: Job[], actor: string,
  fromDate?: string, toDate?: string,
) {
  const doc = new jsPDF();
  const rangeLabel = fromDate || toDate
    ? ` (${fromDate || "start"} – ${toDate || "now"})`
    : "";
  header(doc, "Applicants per Closing Date", `Vacancy demand by deadline${rangeLabel} — ${new Date().toLocaleDateString()}`);

  const filtered = apps.filter((a) => {
    if (!fromDate && !toDate) return true;
    const d = new Date(a.date);
    if (fromDate && d < new Date(fromDate)) return false;
    if (toDate && d > new Date(toDate)) return false;
    return true;
  });

  const jobMap = new Map(jobs.map((j) => [j.id, j]));
  const byJob: Record<number, { title: string; closes: string; count: number }> = {};
  filtered.forEach((a) => {
    if (!a.jobId) return;
    const j = jobMap.get(a.jobId);
    if (!byJob[a.jobId]) byJob[a.jobId] = { title: j?.title ?? `Job #${a.jobId}`, closes: j?.closes ?? "—", count: 0 };
    byJob[a.jobId].count++;
  });

  const rows = Object.values(byJob)
    .sort((a, b) => b.count - a.count)
    .map((v) => [v.title, v.closes, v.count]);

  autoTable(doc, {
    startY: 65,
    head: [["Job Title", "Closing Date", "Applications Received"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  footer(doc, actor);
  doc.save(`caa-applicants-per-closing-date-${Date.now()}.pdf`);
}