/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobRouteImport } from './routes/job'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vacancies': typeof VacanciesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/job'
    | '/login'
    | '/register'
    | '/vacancies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/job'
    | '/login'
    | '/register'
    | '/vacancies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/job'
    | '/login'
    | '/register'
    | '/vacancies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  DashboardRoute: typeof DashboardRoute
  JobRoute: typeof JobRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VacanciesRoute: typeof VacanciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  DashboardRoute: DashboardRoute,
  JobRoute: JobRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VacanciesRoute: VacanciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
